#!/usr/bin/env sh

if [ -z "$GITHUB_WORKSPACE" ]; then
	WORKSPACE='.'
else
	WORKSPACE="$GITHUB_WORKSPACE"
	printf "%s" "$DEPLOY_CONFIG" >"deploy.json"
fi

DISTRO="$1"
shift

docker run --rm \
	-v "${WORKSPACE}":/workspace \
	-w /workspace \
	"ghcr.io/thekhanj/deploy-$DISTRO:latest" \
	bash -c "sudo chown builder:builder . -R && ./deploy $*"
