name: Release ella to AUR

on:
  workflow_dispatch:

jobs:
  release-ella:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Create deploy.json
        run: echo "${{ secrets.DEPLOY_CONFIG }}" > deploy.json

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Run deploy in container
        run: |
          docker run --rm \
            -v $GITHUB_WORKSPACE:/workspace \
            -w /workspace \
            ghcr.io/thekhanj/deploy-arch:latest \
            sh -c './deploy aur/ella update'

  release-ella-bin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Create deploy.json
        run: echo "${{ secrets.DEPLOY_CONFIG }}" > deploy.json

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Run deploy in container
        run: |
          docker run --rm \
            -v $GITHUB_WORKSPACE:/workspace \
            -w /workspace \
            ghcr.io/thekhanj/deploy-arch:latest \
            sh -c './deploy aur/ella update_bin'
